FROM node:18-alpine AS builder

# Set destination for COPY
WORKDIR /app

# Download npm packages
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy the source code.
COPY . .

# Build the Next.js app
RUN yarn build

# Use a lightweight web server for the final stage
FROM node:18-alpine

WORKDIR /app

# Copy the built application and essential files from the builder stage
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/yarn.lock ./yarn.lock

# Install only production dependencies in the final image
RUN yarn install --production --frozen-lockfile

# Expose the port on which the app will run
EXPOSE 3000

# Set environment variable to production
ENV NODE_ENV=production

# Run the Next.js app
CMD ["yarn", "start"]