FROM node:18-alpine AS builder

# Set destination for COPY
WORKDIR /app

# Download npm packages
COPY package.json ./
COPY package.json.lock ./
RUN npm ci

# Copy the source code.
COPY . .

# Build the Next.js app
RUN npm run build

# Use a lightweight web server for the final stage
FROM node:18-alpine

WORKDIR /app

# Copy the built application and essential files from the builder stage
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package.json.lock ./package.json.lock

# Install only production dependencies in the final image
RUN npm install --omit=dev

# Expose the port on which the app will run
EXPOSE 3000

# Set environment variable to production
ENV NODE_ENV=production

# Run the Next.js app
CMD ["npm", "start"]