name: Build and Push Docker Image

# Run this workflow on every push to the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx (multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Docker does not have an option to specify which ignore file to use
      - name: Rename .containerignore to .dockerignore
        working-directory: frontend
        run: mv .containerignore .dockerignore

      # Build the Docker image using the Dockerfile
      - name: Build Docker image
        working-directory: frontend
        run: docker build -f Containerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest .

      # TODO: Add condition to only push on merge request
      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest

      # TODO: Add condition to only check pull on merge request
      # Verify the image exists in Docker Hub
      - name: Verify Docker image exists
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest

      # Post build cleanup to avoid overloading runner
      - name: Remove Docker dangling images
        run: docker image prune -f
